reference_floor: 0
floor_measurements:
-
    floor_number: 0
    mean_pressure_diff: 0.0
-
    floor_number: 1
    mean_pressure_diff: -0.5
-
    floor_number: 2
    mean_pressure_diff: -1.0
pressure_diff_tolerance: 0.25
redundant_measurement_count: 4
filter_window_size: 5
